name: Matrix testing
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Test the action on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'macos-latest', 'windows-latest' ]
        opencv: [ '3.4.10', '4.0.0', '4.6.0' ]
        include:
          - opencv: '3.4.10'
            cpp: '11'
          - opencv: '4.0.0'
            cpp: '14'
          - opencv: '4.6.0'
            cpp: '17'
            
    steps:
      - uses: actions/checkout@v2
      - name: Setup OpenCV ${{ matrix.opencv }} (c++${{ matrix.cpp }})
        uses: ./ # Uses an action in the root directory
        with:
          opencv-version: ${{ matrix.opencv }}
          WITH_IPP: if ${{ matrix.os }} == 'windows-latest' then 'OFF' else 'ON'
          WITH_TBB: if ${{ matrix.os }} == 'windows-latest' then 'OFF' else 'ON'
          ENABLE_PRECOMPILED_HEADERS: if ${{ matrix.os }} == 'windows-latest' then 'OFF' else 'ON'
          CMAKE_CXX_STANDARD: ${{ matrix.cpp }}
